version: '3.8'


volumes:
  db:
  rabbitmq:


services:
  db:
    image: mariadb:10.5.12
    container_name: db
    restart: always
    env_file:
      - .config/envs/db.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql:rw

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
