version: '3.8'


volumes:
  db:


services:
  db:
    image: mariadb:10.5.12
    container_name: db
    restart: always
    env_file:
      - .config/envs/db.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql:rw
