eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:discovery}:8081/eureka

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: gateway
    timezone: ${TIMEZONE:America/Sao_Paulo}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  output:
    ansi:
      enabled: ALWAYS
