eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
        defaultZone: http://${DISCOVERY_HOST:discovery}:8081/eureka

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${TIMEZONE:America/Sao_Paulo}
  level:
    root: ${LOG_LEVEL:info}

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  application:
    name: discovery
    timezone: ${TIMEZONE:America/Sao_Paulo}
  output:
    ansi:
      enabled: ALWAYS
